import{S as P}from"./assets/vendor-B-WyX8ve.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))a(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function e(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(r){if(r.ep)return;r.ep=!0;const s=e(r);fetch(r.href,s)}})();const S="https://pixabay.com/api/",E="53408779-ee8ac1d107b84f4a01a68d938Y",v=15;async function m(t,o=1){const e=new URL(S);e.searchParams.set("key",E),e.searchParams.set("q",t.trim()),e.searchParams.set("image_type","photo"),e.searchParams.set("orientation","horizontal"),e.searchParams.set("safesearch","true"),e.searchParams.set("per_page",String(v)),e.searchParams.set("page",String(o));try{const a=await fetch(e.toString());if(!a.ok)throw new Error(`Pixabay API error: ${a.status}`);return await a.json()}catch(a){throw a}}const n={gallery:document.querySelector(".gallery"),loader:document.querySelector("#loader"),loadMoreBtn:document.querySelector("#load-more")},q=new P(".gallery a",{captionsData:"alt",captionDelay:250});function y(t){t&&t.classList.remove("is-hidden")}function g(t){t&&t.classList.add("is-hidden")}function h(t=[]){if(!n.gallery)return;const o=t.map(e=>`
      <li class="photo-card">
        <a class="gallery__link" href="${e.largeImageURL}">
          <img class="gallery__image" src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b><span>${e.likes}</span></p>
          <p class="info-item"><b>Views</b><span>${e.views}</span></p>
          <p class="info-item"><b>Comments</b><span>${e.comments}</span></p>
          <p class="info-item"><b>Downloads</b><span>${e.downloads}</span></p>
        </div>
      </li>`).join("");n.gallery.insertAdjacentHTML("beforeend",o),q.refresh()}function _(){n.gallery&&(n.gallery.innerHTML="")}function p(){y(n.loader)}function u(){g(n.loader)}function w(){y(n.loadMoreBtn)}function i(){g(n.loadMoreBtn)}const f={form:document.querySelector("#search-form"),input:document.querySelector("#search-input"),loadMoreBtn:document.querySelector("#load-more"),gallery:document.querySelector(".gallery"),loader:document.querySelector("#loader")};let d="",c=1;const L=15;i();u();f.form.addEventListener("submit",$);f.loadMoreBtn.addEventListener("click",B);async function $(t){t.preventDefault();const o=f.input.value.trim();if(!o){iziToast.warning({title:"Warning",message:"Please enter a search query."});return}const e=o.toLowerCase()!==d.toLowerCase();e&&(c=1,_()),d=o,i(),p();try{const a=await m(d,c),{hits:r=[],totalHits:s=0}=a;if(!r.length){u(),iziToast.error({title:"No results",message:`No images found for "${d}".`});return}h(r);const l=c*L;s>l?w():(i(),iziToast.info({title:"End",message:"We're sorry, but you've reached the end of search results."})),!e&&r.length&&b(),iziToast.success({title:"Success",message:`Found ${s} images.`})}catch(a){console.error(a),iziToast.error({title:"Error",message:"Something went wrong. Please try again."})}finally{u()}}async function B(){c+=1,p(),i();try{const t=await m(d,c),{hits:o=[],totalHits:e=0}=t;if(!o.length){u(),iziToast.info({title:"End",message:"We're sorry, but you've reached the end of search results."}),i();return}h(o);const a=c*L;e>a?w():(i(),iziToast.info({title:"End",message:"We're sorry, but you've reached the end of search results."})),b()}catch(t){console.error(t),iziToast.error({title:"Error",message:"Failed to load more images."})}finally{u()}}function b(){const t=f.gallery.querySelector(".photo-card");if(!t)return;const{height:o}=t.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
