import{a as S,S as q,i}from"./assets/vendor-CVuRD470.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const p of n.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&s(p)}).observe(document,{childList:!0,subtree:!0});function o(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerPolicy&&(n.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?n.credentials="include":r.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(r){if(r.ep)return;r.ep=!0;const n=o(r);fetch(r.href,n)}})();const E="https://pixabay.com/api/",v="53408779-ee8ac1d107b84f4a01a68d938",P=15;async function m(e,t=1){const o={key:v,q:e.trim(),image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:P,page:t};try{return(await S.get(E,{params:o})).data}catch(s){throw s}}const a={gallery:document.querySelector(".gallery"),loader:document.querySelector("#loader"),loadMoreBtn:document.querySelector("#load-more")},R=new q(".gallery a",{captionsData:"alt",captionDelay:250});function y(e){e&&e.classList.remove("is-hidden")}function h(e){e&&e.classList.add("is-hidden")}function L(e=[]){if(!a.gallery)return;const t=e.map(o=>`
      <li class="photo-card">
        <a class="gallery__link" href="${o.largeImageURL}">
          <img class="gallery__image" src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b><span>${o.likes}</span></p>
          <p class="info-item"><b>Views</b><span>${o.views}</span></p>
          <p class="info-item"><b>Comments</b><span>${o.comments}</span></p>
          <p class="info-item"><b>Downloads</b><span>${o.downloads}</span></p>
        </div>
      </li>`).join("");a.gallery.insertAdjacentHTML("beforeend",t),R.refresh()}function f(){a.gallery&&(a.gallery.innerHTML="")}function w(){y(a.loader)}function g(){h(a.loader)}function _(){y(a.loadMoreBtn)}function c(){h(a.loadMoreBtn)}const d={form:document.querySelector("#search-form"),input:document.querySelector("#search-input"),loadMoreBtn:document.querySelector("#load-more"),gallery:document.querySelector(".gallery")};let u="",l=1;const B=15;c();g();d.form.addEventListener("submit",M);d.loadMoreBtn.addEventListener("click",$);async function M(e){e.preventDefault();const t=d.input.value.trim();if(!t){f(),c(),i.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}(t.toLowerCase()!==u.toLowerCase()||l>1)&&(l=1,f()),u=t,c(),w();try{const s=await m(u,l),{hits:r=[],totalHits:n=0}=s;if(!r.length){i.error({title:"No results",message:`Sorry, there are no images matching your search query: "${u}". Please try again.`,position:"topRight"});return}L(r),b(n),i.success({title:"Success",message:`Found ${n} images.`,position:"topRight"})}catch(s){console.error(s),f(),i.error({title:"Error",message:"Something went wrong. Please try again.",position:"topRight"})}finally{g(),d.form.reset()}}async function $(){l+=1,w(),c();try{const e=await m(u,l),{hits:t=[],totalHits:o=0}=e;if(!t.length){c(),i.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}L(t),A(),b(o)}catch(e){console.error(e),i.error({title:"Error",message:"Failed to load more images.",position:"topRight"})}finally{g()}}function b(e){const t=l*B;e>t?_():(c(),t>0&&e>0&&i.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}function A(){if(!d.gallery.querySelector(".photo-card"))return;const t=d.gallery.querySelectorAll(".photo-card:nth-last-child(-n+15)");if(t.length===0)return;const{height:o}=t[0].getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
