import{S as b,i}from"./assets/vendor-De63neY_.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))a(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const m of s.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&a(m)}).observe(document,{childList:!0,subtree:!0});function e(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(o){if(o.ep)return;o.ep=!0;const s=e(o);fetch(o.href,s)}})();const P="https://pixabay.com/api/",E="53408779-ee8ac1d107b84f4a01a68d938",q=15;async function p(t,r=1){const e=new URL(P);e.searchParams.set("key",E),e.searchParams.set("q",t.trim()),e.searchParams.set("image_type","photo"),e.searchParams.set("orientation","horizontal"),e.searchParams.set("safesearch","true"),e.searchParams.set("per_page",String(q)),e.searchParams.set("page",String(r));try{const a=await fetch(e.toString());if(!a.ok)throw new Error(`Pixabay API error: ${a.status} ${a.statusText}`);return await a.json()}catch(a){throw a}}const n={gallery:document.querySelector(".gallery"),loader:document.querySelector("#loader"),loadMoreBtn:document.querySelector("#load-more")},R=new b(".gallery a",{captionsData:"alt",captionDelay:250});function g(t){t&&t.classList.remove("is-hidden")}function y(t){t&&t.classList.add("is-hidden")}function w(t=[]){if(!n.gallery)return;const r=t.map(e=>`
      <li class="photo-card">
        <a class="gallery__link" href="${e.largeImageURL}">
          <img class="gallery__image" src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b><span>${e.likes}</span></p>
          <p class="info-item"><b>Views</b><span>${e.views}</span></p>
          <p class="info-item"><b>Comments</b><span>${e.comments}</span></p>
          <p class="info-item"><b>Downloads</b><span>${e.downloads}</span></p>
        </div>
      </li>`).join("");n.gallery.insertAdjacentHTML("beforeend",r),R.refresh()}function f(){n.gallery&&(n.gallery.innerHTML="")}function L(){g(n.loader)}function h(){y(n.loader)}function v(){g(n.loadMoreBtn)}function l(){y(n.loadMoreBtn)}const d={form:document.querySelector("#search-form"),input:document.querySelector("#search-input"),loadMoreBtn:document.querySelector("#load-more"),gallery:document.querySelector(".gallery")};let u="",c=1;const $=15;l();h();d.form.addEventListener("submit",_);d.loadMoreBtn.addEventListener("click",B);async function _(t){t.preventDefault();const r=d.input.value.trim();if(!r){f(),l(),i.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}(r.toLowerCase()!==u.toLowerCase()||c>1)&&(c=1,f()),u=r,l(),L();try{const a=await p(u,c),{hits:o=[],totalHits:s=0}=a;if(!o.length){i.error({title:"No results",message:`Sorry, there are no images matching your search query: "${u}". Please try again.`,position:"topRight"});return}w(o),S(s),i.success({title:"Success",message:`Found ${s} images.`,position:"topRight"})}catch(a){console.error(a),f(),i.error({title:"Error",message:"Something went wrong. Please try again.",position:"topRight"})}finally{h(),d.form.reset()}}async function B(){c+=1,L(),l();try{const t=await p(u,c),{hits:r=[],totalHits:e=0}=t;if(!r.length){l(),i.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}w(r),M(),S(e)}catch(t){console.error(t),i.error({title:"Error",message:"Failed to load more images.",position:"topRight"})}finally{h()}}function S(t){const r=c*$;t>r?v():(l(),r>0&&t>0&&i.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}function M(){if(!d.gallery.querySelector(".photo-card"))return;const r=d.gallery.querySelectorAll(".photo-card:nth-last-child(-n+15)");if(r.length===0)return;const{height:e}=r[0].getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
